-- MySQL Script generated by MySQL Workbench
-- Thu Aug 13 17:23:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema textchat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema textchat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `textchat` DEFAULT CHARACTER SET utf8mb4 ;
USE `textchat` ;

-- -----------------------------------------------------
-- Table `textchat`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `textchat`.`message` (
  `idmessage` INT(11) NOT NULL AUTO_INCREMENT,
  `idsender` VARCHAR(36) NOT NULL,
  `messagecontent` VARCHAR(1000) NOT NULL,
  `time` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`idmessage`))
ENGINE = InnoDB
AUTO_INCREMENT = 814
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `textchat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `textchat`.`user` (
  `iduser` VARCHAR(36) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  `color` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
